apiVersion: v1
kind: Service
metadata:
  labels:
    expose: "true"
    app: reload-service
  name: reload-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: reload-example
  type: NodePort