---
apiVersion: v1
kind: Service
metadata:
  labels:
    expose: "true"
    app: greeting-service
  name: greeting-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: greeting-service
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    expose: "true"
    app: name-service-1
  name: name-service-1
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: name-service-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    expose: "true"
    app: name-service-2
  name: name-service-2
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: name-service-2