---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 1c830172082dc81222b70e01faae9b1549ed2629
    fabric8.io/git-branch: master
    fabric8.io/git-url: https://github.com/seongpyoHong/spring-cloud-kubernetes-example.git
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/kubernetes-hello-world-example
    fabric8.io/scm-tag: HEAD
  labels:
    app: kubernetes-hello-world-example
    provider: fabric8
    version: 0.0.1-SNAPSHOT
    group: com.sphong
  name: kubernetes-hello-world-example
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kubernetes-hello-world-example
      provider: fabric8
      group: com.sphong
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 1c830172082dc81222b70e01faae9b1549ed2629
        fabric8.io/git-branch: master
        fabric8.io/scm-tag: HEAD
        fabric8.io/git-url: https://github.com/seongpyoHong/spring-cloud-kubernetes-example.git
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/kubernetes-hello-world-example
      labels:
        app: kubernetes-hello-world-example
        provider: fabric8
        version: 0.0.1-SNAPSHOT
        group: com.sphong
    spec:
      imagePullSecrets:
      - name: gcr-json-key
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: asia.gcr.io/sphong-kuber/kubernetes-hello-world-example:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
          timeoutSeconds: 30
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          successThreshold: 1
          timeoutSeconds: 30
        securityContext:
          privileged: false
        
